src/controllers/etBlog.controller.ts
src/index.ts
src/routes/etBlog.route.ts
src/services/etBlog.service.ts

- Develop a backend API to retrieve all ET Blog posts from the database. This API will return a list of ET Blog posts based on predefined criteria, including creation date and visibility settings. The front-end will use this API to display blog posts to users.
- Developed GET `/et-blog` endpoint.
- Structured the API response with `highlighted` and `alldata` sections.
- Included metadata: `blog_id`, `title`, `meta_description`, `created_on`, `visible` and `thumbnail_image_url`.
[P2BI-205]: https://techetclub.atlassian.net/browse/P2BI-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-205): build api to get all et blogs

---

src/controllers/etBlog.controller.ts
src/index.ts
src/routes/etBlog.route.ts
src/services/etBlog.service.ts

- This PR implements a backend API that retrieves the details of a specific ET Blog post based on its unique identifier (ID)
- Developed GET `/et-blog/:id` endpoint.
- Included metadata: `blog_id`, `title`, `blog_author`, `visible`, `content`, and `created_on`.
[P2BI-206]: https://techetclub.atlassian.net/browse/P2BI-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-206]: https://techetclub.atlassian.net/browse/P2BI-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-206): build api to get blog details by id

---

src/controllers/etBlog.controller.ts
src/index.ts
src/routes/etBlog.route.ts
src/services/etBlog.service.ts

- Develop a backend API that allows users to delete a ET Blog post.
- Endpoint: DELETE `/et-blog/:id`
- Request parameters: ET Blog ID (path parameter).
- Response: JSON object confirming deletion status.
[P2BI-209]: https://techetclub.atlassian.net/browse/P2BI-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-209]: https://techetclub.atlassian.net/browse/P2BI-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-209): build api to delete a post

---

src/controllers/partner.controller.ts
src/entities/partner.entity.ts
src/index.ts
src/routes/partner.route.ts
src/services/partner.service.ts
src/types/partner.ts

- Develop an API endpoint that allows the creation of a new partner in the system
- Implement an API endpoint to create a new partner
- Validate input data using AJV (JSON Schema Validator).
- Endpoint: `POST /partners`
[P2BI-230]: https://techetclub.atlassian.net/browse/P2BI-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-230]: https://techetclub.atlassian.net/browse/P2BI-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-230): build api to create a new partner

---

src/controllers/partner.controller.ts
src/entities/partner.entity.ts
src/index.ts
src/routes/partner.route.ts
src/services/partner.service.ts
src/types/partner.ts

- Develop an API endpoint that allows updating an existing partner’s details in the system.
- Implement an API endpoint to update an existing partner.
- Validate input data using AJV (JSON Schema Validator).
- Endpoint: PUT /partners/{id}
- Request Parameters: `id` (Path parameter - Unique identifier of the partner to update).
- Request Body: JSON payload with fields to be updated.
[P2BI-234]: https://techetclub.atlassian.net/browse/P2BI-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-234]: https://techetclub.atlassian.net/browse/P2BI-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-234): build api to update partner

---

src/controllers/faq.controller.ts
src/entities/faq.entity.ts
src/index.ts
src/routes/faq.route.ts
src/services/faq.service.ts
src/types/faq.ts

- Developing an API endpoint that allows the creation of a new FAQ (Frequently Asked Question) entry in the system.
- This API validates input data, stores the FAQ details in the database, and returns an appropriate response.
- The implementation follows RESTful API best practices, ensures data integrity, and includes proper error handling.
**Jira Task:** [P2BI-236](https://techetclub.atlassian.net/browse/P2BI-236)
---
- **HTTP method:** `POST`
- **API endpoint:** `/faqs` for creating a new FAQ entry.
[P2BI-236]: https://techetclub.atlassian.net/browse/P2BI-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-236]: https://techetclub.atlassian.net/browse/P2BI-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

feat(P2BI-236): build api to create a new FAQ

---

src/controllers/faq.controller.ts
src/index.ts
src/routes/faq.route.ts
src/services/faq.service.ts
src/types/faq.ts

- Developing an API endpoint that retrieves all FAQs (Frequently Asked Questions) from the system.
- This API queries the database, returns a list of FAQ records, and supports optional filters if applicable.
- The implementation follows RESTful API best practices, ensures data consistency, and includes proper error handling.
**Jira Task:** [P2BI-237](https://techetclub.atlassian.net/browse/P2BI-237)
---
- **HTTP method:** `GET`
- **API endpoint:** `/faqs` for retrieving all FAQ entries.
[P2BI-237]: https://techetclub.atlassian.net/browse/P2BI-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-237]: https://techetclub.atlassian.net/browse/P2BI-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-237): build api to get all faq

---

src/controllers/activity.controller.ts
src/controllers/faq.controller.ts
src/services/activity.service.ts
src/services/faq.service.ts

- Fix returned data to include four fields: aboutETClub, aboutActivities, aboutMembership, and others, sorted by category.
[P2BI-237]: https://techetclub.atlassian.net/browse/P2BI-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(P2BI-237): fix return data

---

package-lock.json
package.json
src/controllers/activity.controller.ts
src/controllers/etBlog.controller.ts
src/controllers/etNews.controller.ts
src/controllers/faq.controller.ts
src/controllers/partner.controller.ts
src/index.ts
src/services/activity.service.ts
src/services/etBlog.service.ts
src/services/etNews.service.ts
src/services/faq.service.ts
src/services/partner.service.ts
src/types/etBlog.ts

This pull request updates the structure of the API response returned
Previously, the frontend depended on hardcoded category keys, which caused issues when new fields were added or modified in the database. 
---
- Refactored service to group items dynamically by category.
- Update response status
---

Fix/API Response Format

---

src/controllers/partner.controller.ts
src/routes/partner.route.ts
src/services/partner.service.ts

- Build API To Update The Visible Field Of Multiple Partners
- Update The Visible Field Of Multiple Partners

feat: build api to update the visible field of multiple partners

---

src/controllers/account.controller.ts
src/index.ts
src/routes/account.route.ts
src/services/account.service.ts

- Build API to get account by ID
- API to get account by ID
- **Endpoint:** `GET '/{id}'`
[P2BI-472]: https://techetclub.atlassian.net/browse/P2BI-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-472]: https://techetclub.atlassian.net/browse/P2BI-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-472): build api to get account by id

---

src/controllers/activity.controller.ts
src/controllers/etBlog.controller.ts
src/controllers/etNews.controller.ts
src/controllers/faq.controller.ts
src/controllers/partner.controller.ts
src/routes/activity.route.ts
src/routes/etBlog.route.ts
src/routes/etNews.route.ts
src/routes/faq.route.ts
src/routes/partner.route.ts
src/services/activity.service.ts
src/services/etBlog.service.ts
src/services/etNews.service.ts
src/services/faq.service.ts
src/services/partner.service.ts

#[Build API To Delete Multiple Records]
- Build API to delete multiple records for Activities, ET Blogs, ET News, FAQs, Partners
- API to delete multiple records for Activities, ET Blogs, ET News, FAQs, Partners
- **Endpoint**: `/bulk-delete`

feature: build api to delete multiple records

---

src/controllers/banner.controller.ts
src/entities/banner.entity.ts
src/index.ts
src/routes/banner.route.ts
src/services/banner.service.ts
src/types/banner.ts

- Build API to create new banner
- API to create new banner
- **Endpoint:** `POST '/'`
[P2BI-544]: https://techetclub.atlassian.net/browse/P2BI-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-544]: https://techetclub.atlassian.net/browse/P2BI-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-544): build api to create new banner

---

src/controllers/banner.controller.ts
src/index.ts
src/routes/banner.route.ts
src/services/banner.service.ts

- Build API to get all banners
- API to get all banners
- **Endpoint:** `GET '/'`
[P2BI-545]: https://techetclub.atlassian.net/browse/P2BI-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-545]: https://techetclub.atlassian.net/browse/P2BI-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-545): build api to get all banners

---

src/controllers/banner.controller.ts
src/index.ts
src/routes/banner.route.ts
src/services/banner.service.ts

- Build API to get banner by ID
- API to get banner by ID
- **Endpoint:** `GET '/{id}'`
[P2BI-546]: https://techetclub.atlassian.net/browse/P2BI-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-546]: https://techetclub.atlassian.net/browse/P2BI-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-546): build api to get banner by id

---

src/controllers/banner.controller.ts
src/index.ts
src/routes/banner.route.ts
src/services/banner.service.ts

- Build API to delete banner and multiple banners
- API to delete banner and multiple banners
- **Endpoint**: `DELETE '/{id}'`, `DELETE '/bulk-delete'`
[P2BI-548]: https://techetclub.atlassian.net/browse/P2BI-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-548]: https://techetclub.atlassian.net/browse/P2BI-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-548): build api to delete banner

---

src/controllers/personnel.controller.ts
src/index.ts
src/routes/personnel.route.ts
src/services/personnel.service.ts
src/types/personnel.ts

- Developing a backend API that allows authorized users to retrieve a list of all personnel records.
- This API fetches data from the database and returns it in a structured JSON format, supporting pagination and filtering if needed.
- HTTP method: `GET`
- API endpoint: `/personnels` for retrieving all personnel records.
[P2BI-376]: https://techetclub.atlassian.net/browse/P2BI-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-376]: https://techetclub.atlassian.net/browse/P2BI-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-376): build api to gell all personnel

---

package-lock.json
package.json
src/controllers/account.controller.ts
src/entities/account.entity.ts
src/index.ts
src/routes/account.route.ts
src/services/account.service.ts
src/types/account.ts
src/utils/email.util.ts

- Build API to create a new account
- API to create a new account
- An email will be sent to user after create account
- **Endpoint:** `POST '/'`
[P2BI-470]: https://techetclub.atlassian.net/browse/P2BI-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-470]: https://techetclub.atlassian.net/browse/P2BI-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-470): build api to create a new account

---

src/controllers/personnel.controller.ts
src/index.ts
src/routes/personnel.route.ts
src/services/personnel.service.ts
src/types/personnel.ts

- Developing a backend API that allows authorized users to retrieve personnel records filtered by their current status.
- This API accepts a status parameter, queries the database accordingly, and returns the matching personnel records in a structured format.
- HTTP method: `GET`
- API endpoint: `/personnels/status/:status` for retrieving personnel by status.
[P2BI-551]: https://techetclub.atlassian.net/browse/P2BI-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-551]: https://techetclub.atlassian.net/browse/P2BI-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-551): build api to get personnel by status

---

src/controllers/personnel.controller.ts
src/entities/personnel.entity.ts
src/index.ts
src/routes/personnel.route.ts
src/services/personnel.service.ts
src/types/personnel.ts

- Developing a backend API that allows authorized users to update an existing personnel record by their ID.
- This API validates the input data, ensures the personnel exists, and updates the personnel and related information in the database.
- HTTP method: `PUT`
- API endpoint: `/personnels/{id}` for updating an existing personnel and personnel_status record.
[P2BI-392]: https://techetclub.atlassian.net/browse/P2BI-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-392]: https://techetclub.atlassian.net/browse/P2BI-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-392): build api to update a personnel

---

src/controllers/personnel.controller.ts
src/index.ts
src/routes/personnel.route.ts
src/services/personnel.service.ts

- Developing a backend API that allows authorized users to delete a personnel record by ID.
- This API checks if the personnel exists, and returns an appropriate response.
- HTTP method: `DELETE`
- API endpoint: `/personnels/{id}` for deleting a specific personnel record.
[P2BI-389]: https://techetclub.atlassian.net/browse/P2BI-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-389]: https://techetclub.atlassian.net/browse/P2BI-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-389): build api to delete a personnel

---

src/controllers/personnel.controller.ts
src/index.ts
src/routes/personnel.route.ts
src/services/personnel.service.ts

- Developing a backend API that allows authorized users to delete multiple personnel records at once by providing a list of IDs.
- This API performs input validation, checks if the personnel exist, and deletes them either softly or permanently based on business logic.
- HTTP method: `DELETE`
- API endpoint: `/personnels` for deleting multiple personnel records using a list of IDs in the request body.
[P2BI-561]: https://techetclub.atlassian.net/browse/P2BI-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-561]: https://techetclub.atlassian.net/browse/P2BI-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-561): build api to delete multiple personnel

---

src/controllers/achievement.controller.ts
src/index.ts
src/routes/achievement.route.ts
src/services/achievement.service.ts
src/types/achievement.ts

- Developing a backend API that allows authorized users to retrieve a specific achievement by its ID.
- This API validates the request, queries the database, and returns the achievement details if found.
- HTTP method: `GET`
- API endpoint: `/achievements/{id}` for retrieving an achievement by its unique ID.
[P2BI-366]: https://techetclub.atlassian.net/browse/P2BI-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-366]: https://techetclub.atlassian.net/browse/P2BI-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-366): build api to get achievement by id

---

src/controllers/achievement.controller.ts
src/index.ts
src/routes/achievement.route.ts
src/services/achievement.service.ts

- Developing a backend API that allows authorized users to delete a specific achievement by ID.
- This API checks if the achievement exists, performs the deletion (soft or hard based on business logic), and returns an appropriate response.
- HTTP method: `DELETE`
- API endpoint: `/achievements/{id}` for deleting an achievement by ID.
[P2BI-373]: https://techetclub.atlassian.net/browse/P2BI-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-373]: https://techetclub.atlassian.net/browse/P2BI-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(P2BI-363): build api to delete achievement

---

src/controllers/partner.controller.ts
src/entities/partner.entity.ts
src/services/partner.service.ts
src/types/partner.ts

- Update partner entity
- Change partner_category_id field to partner_category_name

fix: update partner entity

---

src/controllers/term.controller.ts
src/index.ts
src/routes/term.route.ts
src/services/term.service.ts

- Build API to get all terms
- API to get data from Term table in database
- **Endpoint:** `GET '/'`

feat: build api to get all terms

---

src/services/personnel.service.ts

- Improve Delete Personnel Service
- Delete account before deleting personnel

Fix/ Personnel Delete Service

---

package-lock.json
package.json
src/controllers/auth.controller.ts
src/entities/auth.entity.ts
src/index.ts
src/routes/auth.route.ts
src/services/auth.service.ts
src/types/auth.ts

- Implement API login and JWT generation
- Implement API login and JWT generation
- This API returns an access token, a refresh token, and a user payload containing `account_id`, `personnel_id`, `username`, `sys_role_name`, `issued_at`, and `expiration_at` upon successful login.
- **Endpoint:** `POST '/auth/login'`
[P2BI-570]: https://techetclub.atlassian.net/browse/P2BI-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[P2BI-570]: https://techetclub.atlassian.net/browse/P2BI-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(P2BI-570): implement login api and jwt generation

---

etweb-swagger.yaml

- Add Swagger documentation for API endpoints related to:
- Achievement
- Activity
- ET News
- ET Blog
- Partner
- This update helps developers and QA teams better understand and test these endpoints.
- Contributes to comprehensive API documentation for the project.
- Defined Swagger schemas and routes for achievements, activities, ET news, ET blog, and partners (GET, POST, PUT, DELETE)
- Verified the documentation renders correctly in Swagger UI.

feat: swagger content 1

---

src/database/migrations/create_tables.sql

- Added new tables: `Application` and `Recruitment` according to the Workflow document.
- Updated schema of `Achievement` table by changing the type of `highlight_number`.
- The new tables are required to support the application and recruitment workflow.
- The `highlight_number` column type adjustment ensures correct data storage and consistency.
- Created `Application` table with necessary fields and constraints.
- Created `Recruitment` table with necessary fields and constraints.
- Modified `highlight_number` column type in `Achievement` table.
- Updated related sequences, foreign keys, and constraints where applicable.

chore(US227): adjust db script

---

src/database/migrations/create_tables.sql
src/services/application.service.ts
src/types/personnel.ts

- Fixed issues in the application service logic.
- Improved consistency and reliability when handling application data.
- The service previously had incorrect handling of certain application fields.
- Adjustments were needed to align with the current database schema and workflow.
- Updated application service functions to ensure correct status updates.
- Fixed parameter handling in raw queries.
- Improved error handling and return responses.
- application_name: Nguyễn Thị Mai

fix: update application service
